### PR TITLE
Update wireless-displays--miracast-.md

### PR DESCRIPTION
**Pull request by drewbaron-wifi**
Changing the link here to refer to the new wireless Projection content we just posted to Hardware Dev Center.

### CODE REVIEW

**Comment by drewbaron-wifi** [comment]
Lori, as part of this change can we also remove the old whitepaper from the repo?
https://download.microsoft.com/download/3/F/9/3F9F0453-04AE-4E4B-87EF-729FF931C1F9/Building%20best-in-class%20Miracast%20solutions%20with%20Windows%2010%20.docx

**Comment by lorihollasch** [comment]
@EliotSeattle, can you please remove the whitepaper identified above from downloads.microsoft.com?

**Comment by EliotSeattle** [comment]
@lorihollasch I have unpublished that download. Can you please submit a redirect for that URL to point to the newer content? Otherwise, people will only see a 404 error.

**Comment by lorihollasch** [comment]
@eliotseattle, Drew updated the link so we are all good on this change!

**Pull request merged**
