### PR TITLE
Minor grammar fixes

### PR DESCRIPTION
**Pull request by alex-oswald**
- A few minor grammar fixes
- Some fixes to code blocks that specified a different language than what is used in the block
- Removed some unnecessary whitespace

### CODE REVIEW

**Review by DOMARS — APPROVED** [review]

**Comment by DOMARS** [comment]
@alex-oswald - Thanks very much for this PR. Having the correct syntax highlighting is well worth doing. I found one other topic, that had the CSharp / csharp case mis match. "# Authoring Tests in C#", that we should fix as well.

It looks like you need to sign the contributor's agreement for this GitHub. Let me know, when you have a chance to do that. Thanks again for creating this PR!

**Comment by alex-oswald** [comment]
Hey @DOMARS I'm not seeing another spot in "# Authoring Tests in C#". I did a search of "```CSharp" in the repo and there are 17 results with the case mis-match that I just fixed as well.

**Comment by alex-oswald** [comment]
Got that instance here 99faa470d81b544b608187a5deec4e801135e3be 😃

**Comment by DOMARS** [comment]
@mhopkins-msft - Just FYI we had a sharp eye colleague fix some mixed case code labels, including some in USB. Autocomplete uses all lower case, so these fixes do that.

**Comment by mhopkins-msft** [comment]
Thank you @DOMARS and @alex-oswald

**Pull request merged**
