### PR TITLE
add traditional Chinese annotation

### PR DESCRIPTION
**Pull request by ianchen0119**
In the previous pull request that I create,  I had typed some wrong character, so I was fixed it.

### CODE REVIEW

**Comment by EliotSeattle** [comment]
@tedhudek can you please assign this to the correct loc contact? Thanks!

**Comment by tedhudek** [comment]
@ianchen0119 did you mean to open this PR in the zh-cn doc repo?

**Comment by ianchen0119** [comment]
> @ianchen0119 did you mean to open this PR in the zh-cn doc repo?

yes, thanks a lot.

**Comment by tedhudek** [comment]
Ok, I'll close this one.  Let us know if we can help with the English site.

**Pull request closed without merging**
