### PR TITLE
Updates to clarify privacy shutter/switch requirements

### PR DESCRIPTION
**Pull request by michaelajax**
- Grouped HW design details doc and driver implementation details doc together via table of contents
- Renamed the two docs to be more clear
- Updated "should"/"must" language to match HLK requirements
- Clarified notification API applies to shutters and kill switches
- Clarified that shutters are not required, but notification is required IF a shutter/switch is used on a device

### CODE REVIEW

**Comment by michaelajax** [comment]
@barrygolden I don't know if/how I can test my edits to the table of contents, can you please help me confirm?

Currently, we have the following:
image

and I want to change it to:

```
|--- Camera privacy controls (shutters and kill switches)
|    |--- Camera privacy shutters and kill switches
|    |--- Privacy shutter/switch notification
```

**Review by barrygolden — APPROVED** [review]

**Review by kasumman — APPROVED** [review]

**Review by absubba — APPROVED** [review]

**Comment by NaveenThum** [comment]
@gerritsMSFT is added to the review. #Closed

**Review by NaveenThum — APPROVED** [review]
:shipit:

**Review by etcjenc — APPROVED** [review]

**Comment by michaelajax** [comment]
@barrygolden Ready to complete

**Comment by barrygolden** [comment]
@michaelajax, the PR should be live on docs now.

**Pull request merged**
