### PR TITLE
Update keyboard-and-mouse-hid-client-drivers.md

### PR DESCRIPTION
**Pull request by DJm00n**

### CODE REVIEW

**Comment by DJm00n** [comment]
Page can be viewed now. So go live with it.

**Comment by EliotSeattle** [comment]
@DJm00n are you MSFT FTE?

**Comment by EliotSeattle** [comment]
@billlattimer 
Can you get a product team review on this please, and then determine when to merge?
Thanks,
Eliot

**Comment by billlattimer** [comment]
@EliotSeattle will do.

**Comment by DJm00n** [comment]
@EliotSeattle no, I just open-source contributor. :)

**Comment by EliotSeattle** [comment]
Thanks a million for your help, @DJm00n!!! 
We'll just take a quick look at the changes, then.
Eliot

**Comment by billlattimer** [comment]
@DJm00n this is a great catch on the table error and excellent work to correct it. We're in the process of converting HTML tables to MD tables in our Docs platform, so I've created a work item to correct the table using your work - and convert it to MD at the same time. I'm going to close this PR, but thank you for your work on this!

**Pull request closed without merging**
