### PR TITLE
Network/Bindings: add missing closing bracket

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report  #2008. i added missing closed bracket

### CODE REVIEW

**Comment by illfated** [comment]
PR title suggestion:
**Network/Bindings: add missing closing bracket**

(this says more about where in the documentation this change is made)

**Comment by illfated** [comment]
Technically speaking, from a grammar/semantics perspective, the changed character is a parenthesis ` ( ` , ` ) ` , while the following character ` { ` is a curly brace or curly bracket.

**Comment by RAJU2529** [comment]
@illfated .Changed the title

**Comment by illfated** [comment]
I mean on this page, the page title:

# added closed bracket #2042

**Comment by RAJU2529** [comment]
@illfated . changed

**Comment by illfated** [comment]
Thanks. Looks good to me.

**Comment by illfated** [comment]
#sign-off

**Comment by billlattimer** [comment]
Fix for this pushed under #2008 and published.

**Pull request closed without merging**
