### PR TITLE
Add SSL.com EV Code Signing link

### PR DESCRIPTION
**Pull request by codelux**
I'd like to propose adding SSL.com to the list of EV Code Signing vendors. We are in the Windows Root CA Program and our EV Code Signing certificates are applicable to the contents of the page.

### CODE REVIEW

**Comment by codelux** [comment]
The latest participants to the Windows Root CA Program can be found here https://gallery.technet.microsoft.com/Trusted-Root-Program-381e7a89

**Comment by tedhudek** [comment]
Thanks @codelux, sorry for the delay!

**Comment by codelux** [comment]
Thanks Ted! Do you know when this page should be updated with the merged commit?

https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate

**Comment by tedhudek** [comment]
Now :)

**Comment by codelux** [comment]
much appreciated!

**Pull request merged**
