### PR TITLE
Changed applying status

### PR DESCRIPTION
**Pull request by Van-Fouran**
Due to https://github.com/MicrosoftDocs/windows-driver-docs/issues/1753 and https://social.technet.microsoft.com/Forums/en-US/7b1545e2-7cfd-463a-9a3e-cceca35a8b70/linked-article-wrong?forum=win10itprosecurity this article seems to apply not only to Windows 10 mobile but for other variants of Windows 10, too.

### CODE REVIEW

**Comment by Van-Fouran** [comment]
Is there anything new on this case?

**Comment by Van-Fouran** [comment]
Can I help you somehow on this case?

**Comment by barrygolden** [comment]
Hi @Van-Fouran,

This topic has specific information that makes it applicable only to Windows 10 Mobile.

I added the "applies to" Windows 10 Mobile tag in  the topic at the request of one of the Windows 10 Mobile developers.  

I added this text in the following commit on 5/2/2017:

https://github.com/MicrosoftDocs/windows-driver-docs/commit/b0844b5abca78eec9aef64cdcb960bcef7a7a6cd#diff-f85a392184672414e55e29e2e2996b6e

If you check the illustration and the topic text in the "OEM requirements and considerations"
 section you'll notice several references that indicate that it is focused on Windows 10 Mobile devices.

I appreciate you submitting a pull request, but am unable to accept it. I would encourage you to continue to with the engage on community on the TechNet Forum site in seeking clarification on your questions on secure boot.

Thanks!

**Comment by Van-Fouran** [comment]
Thanks for the feedback.

**Pull request closed without merging**
