### PR TITLE
typo: Double word "before"

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
Build failure appears unrelated to the change

**Comment by EliotSeattle** [comment]
@tedhudek can you look at this? I don't see the error.

**Comment by nschonni** [comment]
@EliotSeattle I filed an issue with the validation service, and https://github.com/MicrosoftDocs/windows-driver-docs/pull/942 seems to indicate it is a bug in the checking

**Comment by EliotSeattle** [comment]
Ah, thanks. @tedhudek I suspect this is what Megan was checking.

**Comment by tedhudek** [comment]
Thanks @nschonni for the PR

**Pull request merged**
