### PR TITLE
Update bug-check-0xc000021a--winlogin-fatal-error.md

### PR DESCRIPTION
**Pull request by jasonepperly**
Fixing the bugcheck name and details.

### CODE REVIEW

**Comment by DOMARS** [comment]
@jasonepperly - Thanks for your interest in keeping the bug check stop codes up to date. I think you may be seeing a NTSTATUS return code of 0x21A? https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55 That is STATUS_SYSTEM_PROCESS_TERMINATED. 

As I look in bugcodes.w it looks like 0x21A is still recorded as WINLOGON_FATAL_ERROR.

**Comment by jasonepperly** [comment]
@Andrew Richards<mailto:Andrew.Richards@microsoft.com>,
I am looking to get our public facing bugcheck content to refer to the 0xc000021a as STATUS_SYSTEM_PROCESS_TERMINATED instead of WINLOGON_FATAL_ERROR<https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xc000021a--winlogin-fatal-error>. This bugcheck occurs whenever a component calls NtRaiseHardError with STATUS_SYSTEM_PROCESS_TERMINATED. This is done in:

Places where we are calling NtRaiseHardError with STATUS_SYSTEM_PROCESS_TERMINATED (which always results in the bugcheck 0xC000021A)

  *   smss!SmpTerminate - SMSS.exe failing
  *   bootshsvc!TerminateWithError
  *   CSRSRV!CsrUnhandledExceptionFilter - CSRSS.exe failing
  *   PogoFatalExit
  *   services!CRebootContext::Perform - Services.exe fail

The WINLOGON_FATAL_ERROR constant seems to only be used by code reading bugcheck parameters. I can't find ANY OS component actually bugchecking or calling NtRaiseHardError with this constant.

Problem is that !analyze is still reporting this as WINLOGON_FATAL_ERROR which I suspect is because this is the CONSTANT name for this bugcheck code in bugcodes.w, bugcodes.mc, and bugcodes.h.


kd> !analyze -show

WINLOGON_FATAL_ERROR (c000021a)

The Winlogon process terminated unexpectedly.

Arguments:

Arg1: ffff89070e84ab30, String that identifies the problem.

Arg2: 00000000c000017d, Error Code.

Arg3: 0000000000000000

Arg4: 0000000000000000


I am working on a lot of these cases and finding they are all getting mis-routed and mis-diagnosed by front-line engineers (and customers) as "I must be having a problem with Winlogon". In reality it is more likely a problem with initialization in SMSS, CSRSS, or SCM.




What do you think?

Jason

**Comment by jasonepperly** [comment]
Agreed, the reuse needs to be fixed/addressed.

Everything comes from bugcodes.w - the value, name and text. If we update it, and all callers, it’ll update everything downstream.

+Don (doc author)
+REL

Any comments anyone?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Jason Epperly <jasone@microsoft.com>
Sent: Friday, September 11, 2020 6:00:24 AM
To: MicrosoftDocs/windows-driver-docs <reply@reply.github.com>; MicrosoftDocs/windows-driver-docs <windows-driver-docs@noreply.github.com>; Andrew Richards <Andrew.Richards@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/windows-driver-docs] Update bug-check-0xc000021a--winlogin-fatal-error.md (#2483)


@Andrew Richards<mailto:Andrew.Richards@microsoft.com>,

I am looking to get our public facing bugcheck content to refer to the 0xc000021a as STATUS_SYSTEM_PROCESS_TERMINATED instead of WINLOGON_FATAL_ERROR<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows-hardware%2Fdrivers%2Fdebugger%2Fbug-check-0xc000021a--winlogin-fatal-error&data=02%7C01%7CAndrew.Richards%40microsoft.com%7Cde68b096b7fd44fc42d508d85652a665%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637354260341694097&sdata=uAUhD8%2FhT3drqdeYZV8%2FOfA5GXI9PFk0Z543VVw55ow%3D&reserved=0>. This bugcheck occurs whenever a component calls NtRaiseHardError with STATUS_SYSTEM_PROCESS_TERMINATED. This is done in:



Places where we are calling NtRaiseHardError with STATUS_SYSTEM_PROCESS_TERMINATED (which always results in the bugcheck 0xC000021A)

  *   smss!SmpTerminate - SMSS.exe failing
  *   bootshsvc!TerminateWithError
  *   CSRSRV!CsrUnhandledExceptionFilter - CSRSS.exe failing
  *   PogoFatalExit
  *   services!CRebootContext::Perform - Services.exe fail



The WINLOGON_FATAL_ERROR constant seems to only be used by code reading bugcheck parameters. I can't find ANY OS component actually bugchecking or calling NtRaiseHardError with this constant.



Problem is that !analyze is still reporting this as WINLOGON_FATAL_ERROR which I suspect is because this is the CONSTANT name for this bugcheck code in bugcodes.w, bugcodes.mc, and bugcodes.h.



kd> !analyze -show

WINLOGON_FATAL_ERROR (c000021a)

The Winlogon process terminated unexpectedly.

Arguments:

Arg1: ffff89070e84ab30, String that identifies the problem.

Arg2: 00000000c000017d, Error Code.

Arg3: 0000000000000000

Arg4: 0000000000000000



I am working on a lot of these cases and finding they are all getting mis-routed and mis-diagnosed by front-line engineers (and customers) as "I must be having a problem with Winlogon". In reality it is more likely a problem with initialization in SMSS, CSRSS, or SCM.





What do you think?



Jason

**Comment by jasonepperly** [comment]
Taking conversation offline

**Pull request closed without merging**
