### PR TITLE
Update troubleshooting-driver-signing-installation.md #2389 write-the-docs-2020

### PR DESCRIPTION
**Pull request by sajeanp**
updated for "click" instances; several paragraphs rewritten for clarity

### CODE REVIEW

**Comment by tedhudek** [comment]
Great fixes here, Susan, thanks again!

**Comment by sajeanp** [comment]
Pretty much the same thing I do every day at my workplace when I have to figure out what our SME's software and network troubleshooting notes really mean :-)

**Comment by tedhudek** [comment]
Yes!  We speak the same language :)

**Comment by sajeanp** [comment]
A pleasure to work with you remotely :-) I'm hoping to show up at future WtD events (for sure, I'll attend the October Prague virtual conference)

**Pull request merged**
