### PR TITLE
Update windbg-what-is-new-preview.md

### PR DESCRIPTION
**Pull request by asklar**

### CODE REVIEW

**Comment by asklar** [comment]
@DOMARS I noticed the link to -srcpath---lsrcpath--set-source-path-.md  is broken (doesn't render as a link), any idea how to fix that?

**Comment by DOMARS** [comment]
@asklar - Thanks for this PR and typo fixes! We have some link automation which may have caused the link issue. 

In short, links should be `[]()`, not `()[]`.

```
[Source Code Extended Access](source-code-extended-access.md)
```

So:

```
[.srcpath, .lsrcpath (Set Source Path)](-srcpath---lsrcpath--set-source-path-.md)
``` 
[.srcpath, .lsrcpath (Set Source Path)](-srcpath---lsrcpath--set-source-path-.md)

Let me know if you would like to fix that link, or I'm happy to as well.

**Comment by asklar** [comment]
thank you @DOMARS, fixed :)

**Comment by DOMARS** [comment]
@asklar - Thank you!

**Pull request merged**
