### PR TITLE
Update choosing-a-32-bit-or-64-bit-debugger-package.md

### PR DESCRIPTION
**Pull request by RAJU2529**
added link   **https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/**

article link
**https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/choosing-a-32-bit-or-64-bit-debugger-package**

after adjustment,  below is the output
Screenshot 2023-10-24 164118

### CODE REVIEW

**Comment by RAJU2529** [comment]
@DOMARS , I found two links , but i added second in this article

**[install Debugging Tools for Windows](index.md)**.

**[install Debugging Tools for Windows](https://learn.microsoft.com/windows-hardware/drivers/debugger)**

**Comment by DOMARS** [comment]
@RAJU2529 - As much as possible, we try and match the article title to the link text. Also, we use relative links to topics that are located elsewhere in the docs, to support the off line use of the docs. In this case the topic is in the same directory, so we add the .md file extension. So can you update the target link to this:
` [Debugging Tools for Windows](debugger-download-tools.md)`

**Review by RAJU2529 — COMMENTED** [review]
@DOMARS . Just now i updated it.

**Review by DOMARS — APPROVED** [review]
Looks good, thanks.

**Comment by RAJU2529** [comment]
@DOMARS Sir I have created taskbar layout modification XML file and posted in Microsoft answer forum.
Wil you check it for a while if you have free time.

https://answers.microsoft.com/en-us/windows/forum/all/how-to-create-taskbar-layoutmodificationxml-file/0d95da23-85d1-47d2-a9c4-c3f5bc31c88a

**Pull request merged**
