### PR TITLE
Update ksproperty-cameracontrol-extended-eyegazecorrection.md and sample code to match new DDI spec

### PR DESCRIPTION
**Pull request by strongstrongyiwen**
Modified statements about bit logic that STARE needs to be set together with ON to make effect, and updated sample code, to match new DDI spec.

### CODE REVIEW

**Comment by strongstrongyiwen** [comment]
@barrygolden @Sudhaushu @kasumman @NaveenThum This is the PR to update the bit logic in eyegazecorrection msdn and sample code, similar to the just completed backgroundsegmentation one. Please review and sign off if everything looks okay. Thanks!

**Comment by NaveenThum** [comment]
@LPBourret is added to the review. #Closed

**Comment by NaveenThum** [comment]
@j-leungyy is added to the review. #Closed

**Comment by NaveenThum** [comment]
@chrilaMSFT is added to the review. #Closed

**Comment by NaveenThum** [comment]
@jiteshkris is added to the review. #Closed

**Comment by NaveenThum** [comment]
@microkatz is added to the review. #Closed

**Comment by NaveenThum** [comment]
@absubba is added to the review. #Closed

**Review by NaveenThum — APPROVED** [review]
:shipit:

**Review by barrygolden — APPROVED** [review]

**Comment by barrygolden** [comment]
@strongstrongyiwen, let me know when reviewers have signed off and this PR is ready to merge.

**Review by kasumman — APPROVED** [review]

**Comment by strongstrongyiwen** [comment]
> @strongstrongyiwen, let me know when reviewers have signed off and this PR is ready to merge.

Thanks Barry, this PR is ready to merge. @barrygolden

**Pull request merged**
