### PR TITLE
Update bug-check-0xe--no-user-mode-context.md

### PR DESCRIPTION
**Pull request by longm0de**
Additional data about this bug check.

### CODE REVIEW

**Comment by duncanmacmichael** [comment]
Hi @jasonfish4 , that's good feedback. Thanks so much for your interest in improving the docs. For bug check topics, we need to perform further investigation with the feature team to ensure we have the proper messaging on the page, so we can't update the page immediately but we will get the ball rolling for it.

For now, we'll leave the PR open and circle back once we have an answer from the right stakeholders on the best wording for this. Thanks again!

**Comment by DOMARS** [comment]
Hi @jasonfish4, we have completed the initial research on this and are working with the dev team to investigate how to describe this bug check. There is draft text under review, so I hope we can provide updated text on this topic in another week or two. Thanks for your interest in improving our docs and sharing your experience with this bug check code.

**Comment by longmode** [comment]
Thanks for responding. I understand.

**Comment by DOMARS** [comment]
@longmode - I'm following up with the dev team to see if we can move this forward.

**Comment by DOMARS** [comment]
@longm0de - Sorry for the lengthy delay here. Seeing if I can push the dev team forward on this.

**Comment by DOMARS** [comment]
@longm0de - I worked with the dev team on updated wording for the 0xe--no-user-mode-context stop code. That wording from the dev team is now live, so closing this PR. Thanks for the proposed wording that you provided in this PR. And thanks for your interest in improving the stop code documentation.

**Pull request closed without merging**
