### PR TITLE
update language (hopefully table is not off?)

### PR DESCRIPTION
**Pull request by selerner**
need to check if the table is still fine...

### CODE REVIEW

**Comment by selerner** [comment]
@EliotSeattle is there any way to see the changes when doing a "patch" change to make sure i didn't mess up the markdown table?

**Comment by EliotSeattle** [comment]
@selerner 
If you go to the Files changed tab, on the top right of the form, there's an icon for raw data that looks like: <> and to the right of it there's an icon for "Display the rich diff" that looks like a page or doc. Click that for a rendering. It doesn't get everything (metadata shows weird and a couple of things like that) but it's pretty good fidelity.

**Comment by selerner** [comment]
@EliotSeattle awesome! thanks for the tip!  It seems to look good, could we complete this PR when you get a chance?

**Comment by EliotSeattle** [comment]
Done, @selerner

**Comment by selerner** [comment]
Thank you!

**Pull request merged**
