### PR TITLE
Fix for duplicate lines.

### PR DESCRIPTION
**Pull request by AlphaLionByte**
Lines 56 and 58 are duplicate.

### CODE REVIEW

**Comment by EliotSeattle** [comment]
Thanks for catching this, @AlphaLionByte

**Comment by AlphaLionByte** [comment]
Hello, @EliotSeattle! I'm a russian student and I am studying Windows driver development. Is there any possible way to write a translation for driver docs (and other articles) on MS site (maybe just like this pull request)? My russian language level is good (same for technical). I think, it will be a good practice for me in technical English and win driver theory. I've read articles about Markdown and Git Bash.

I had already googled for my question, but did not receive results.

**Comment by EliotSeattle** [comment]
Hi @AlphaLionByte 
Sorry I didn't get back to you sooner, but right now we don't have the ability to accept community translations. We're just not able to scale up to review unscheduled content. I would encourage you to go ahead and write whatever content you can and [ublish it on a blog or any other place you can find. My experience has been that writing about a technology for others to read makes me really have to understand what I'm talking about. :-)
I wish I had better news than that.
Eliot

**Comment by AlphaLionByte** [comment]
Thanks a lot, @EliotSeattle!

Philipp

**Pull request merged**
