### PR TITLE
added abbreviation for mat  madt

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report  #2521 , so i added abbrevation,
also, I added many abbreviations

### CODE REVIEW

**Comment by ole-h** [comment]
MAIN

**Comment by ole-h** [comment]
README-EDITS

**Comment by RAJU2529** [comment]
@tedhudek . Is there any changes from my side to this PR

**Review by barrygolden — APPROVED** [review]

**Comment by barrygolden** [comment]
@RAJU2529, thanks for the PR and your ongoing contributions to the docs!

**Pull request merged**
