### PR TITLE
address feedback on Bluetooth HCI Extension appendix

### PR DESCRIPTION
**Pull request by erikpe-msft**
We received feedback from a partner that the recently-added appendix to the Bluetooth HCI Extensions had some technical issues. This change addresses those issues and also clarifies one point earlier in the spec.

### CODE REVIEW

**Comment by erikpe-msft** [comment]
FYI, @m-robertz

**Comment by erikpe-msft** [comment]
@m-robertz is added to the review. #Closed

**Comment by m-robertz** [comment]
Approved since commit b5d9a96f4abaab08547c19dadf267cffd9296078

**Comment by mhopkins-msft** [comment]
@erikpe-msft is this ready to go?

**Comment by erikpe-msft** [comment]
> @erikpe-msft is this ready to go?

@mhopkins-msft: Yup! I'm good with the change and so is @robertz-msft

**Pull request merged**
