### PR TITLE
Update getting-started-with-universal-drivers.md

### PR DESCRIPTION
**Pull request by noishiza**
I request to update a document about universal windows driver because it is not specified the target device type in the document. This guidance is for in-box driver, not for add-on device driver.

### CODE REVIEW

**Comment by tedhudek** [comment]
Hi @noishiza thanks for the PR.  I think that this guidance applies to all 3rd party drivers, not just inbox.  Can you provide more info on why you think this is for inbox drivers only?

Adding @selerner fyi

**Comment by noishiza** [comment]
Hi Ted,
Sorry, please pend this request.
I am confirming this to PG now.

Regards,
Nozomu

**Comment by tedhudek** [comment]
Hi @noishiza checking back on this one.  Do you have any more info?

**Comment by noishiza** [comment]
Hi @tedhudek, I withdraw this request. I'm sorry to trouble you.

**Comment by tedhudek** [comment]
No problem at all @noishiza!  Please let us know if we can help in the future.

**Pull request closed without merging**
