### PR TITLE
Update setting-up-a-connection-to-a-virtual-machine-in-visual-studio.md

### PR DESCRIPTION
**Pull request by YouRancestor**
Visual Studio should be run as administrator when starting the debugging session.

### CODE REVIEW

**Comment by DOMARS** [comment]
Duncan, in your experience would you launch VS as admin to debug when working back in the older versions of Windows that supported this?

**Comment by duncanmacmichael** [comment]
When I was setting up a connection to a virtual machine in VS, I don't recall having to run VS as administrator, no. At the time I was using VS 2017 Enterprise, Windows 10, version 1709, and the 1709 version of the WDK. It could be different for older versions of Windows or VS but I can't say with 100% certainty. Perhaps we could add running as admin as an optional tip if someone encounters an error while starting the debugging session?

**Comment by YouRancestor** [comment]
@DOMARS 
I received this error from Visual Studio:

> Windows Debugging Extension for Visual Studio
Could not start debug session, error 80070005: Access denined.

With Visual Studio Community 2017 15.7.3, Windows 10 Professional 64bit (10.0, version 17134), Windows Driver Kit - Windows 10.0.17134.1, and the virtual machine is the default Windows 10 dev environment(Enterprise Evaluation) provided by Hyper-V.

**Comment by DOMARS** [comment]
@YouRancestor Thanks for this input. After looking at this, I ended up adding a tip relating to running as admin. That change is now live in the topic. 
You should be aware that you are running a version of the WDK that is newer then the last supported version (1507) for this functionality. 
Good luck with your debugging and thanks for this pull request.

**Pull request closed without merging**
