### PR TITLE
Update supported-usb-classes.md

### PR DESCRIPTION
**Pull request by the-Arioch**
404 for usbcon/support-for-interface-collections.md

### CODE REVIEW

**Review by mhopkins-msft — APPROVED** [review]

**Comment by mhopkins-msft** [comment]
Hi @the-Arioch,

Thanks for the update!

 ~ *Mark*

**Comment by the-Arioch** [comment]
@mhopkins-msft sorry, seems not enough

seems you have to also add ".md" to the end of the link

I am not experienced in new markdown-based MSFT docs process, so thought it would be done automatically. I already killed my forked repo, so would not be able to add another commit to the same barnch/PR


I judge by the https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/supported-usb-classes.md

2022-11-16 02_54_18-windows-driver-docs_supported-usb-classes md at staging · MicrosoftDocs_windows-

**Comment by mhopkins-msft** [comment]
Hi @the-Arioch,

Oops, right you are! I've fixed up the issues you mentioned. The article will be republished later today.

Thanks again!
 ~ *Mark*

**Comment by the-Arioch** [comment]
Seems fine now. Thanks!

**Pull request merged**
