### PR TITLE
Update wmi-and-the-power-management-tab.md

### PR DESCRIPTION
**Pull request by Shyamal-V**
Clarify Power Management settings for devices. @tedhudek could you please review or redirect. 

@AndrewYangMSFT

### CODE REVIEW

**Comment by tedhudek** [comment]
Looks fine to me @Shyamal-V.  Do you want Andrew to have a look before I complete?

**Comment by AndrewYangMSFT** [comment]
commit 2 looks good to me.

**Review by AndrewYangMSFT — APPROVED** [review]

**Comment by Shyamal-V** [comment]
@tedhudek is good to go with the latest commit. thanks.

**Comment by tedhudek** [comment]
Thanks guys!

**Pull request merged**
